# -*- coding: utf-8 -*-
"""breast cancer

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1R0vX95YJySygNLXMnM5V8GaiaGhtkgJP
"""

from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix

#load breast cancer data
BreastData = load_breast_cancer()
X = BreastData.data
y = BreastData.target

#Splitting data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=44, shuffle =True)

#Applying LogisticRegression Model 
LRModel = LogisticRegression(penalty='l1',solver='liblinear', C=1.0,random_state=33)
LRModel.fit(X_train, y_train)

#Calculating score
print('Train Score is : ' , LRModel.score(X_train, y_train))
print('Test Score is : ' , LRModel.score(X_test, y_test))

#Applying Prediction
y_pred = LRModel.predict(X_test)

#Calculating Confusion Matrix
CM = confusion_matrix(y_test, y_pred)
print('Confusion Matrix is : \n', CM)
